Cumulative commits which were released with blueCFD-Core 2.3-1.
This commit includes all of the patches, modifications and additions needed for making OpenFOAM build and work on Windows Operating Systems.
It includes changes made by Symscape and FSD blueCAPE, where each one of the modified files should disclaim who made which changes.
A full git development tree is not provided, due to incorrect user-email signing.

If you find any changes that have been made and not properly assigned to their original authors, please report at https://github.com/blueCFD/Core/issues

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -6,8 +6,10 @@
 #   \\  /    A nd           | Copyright (C) 2011-2014 OpenFOAM Foundation
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
+# 2014-02-20 blueCAPE Lda: Modifications for blueCFD-Core 2.3
+#------------------------------------------------------------------------------
 # License
-#     This file is part of OpenFOAM.
+#     This file is a derivative work of OpenFOAM.
 #
 #     OpenFOAM is free software: you can redistribute it and/or modify it
 #     under the terms of the GNU General Public License as published by
@@ -21,6 +23,20 @@
 #
 #     You should have received a copy of the GNU General Public License
 #     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
+#
+# Modifications
+#     This file has been modified by blueCAPE's unofficial mingw patches for
+#     OpenFOAM.
+#     For more information about these patches, visit:
+#         http://bluecfd.com/Core
+#
+#     Modifications made:
+#        - Derived from the patches for blueCFD 2.1 and 2.2.
+#        - Added building capabilities for Zlib and RegEx.
+#        - Added capabilities for building the stubs for: 
+#             Open-MPI, MPICH and MSMPI
+#        - Added capability for building Scotch for MinGW.
+#        - Added patches for TecIO and added back this build option.
 #
 # Script
 #     Allwmake
@@ -43,6 +59,7 @@ wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
     exit 1
 }
 . etc/tools/ThirdPartyFunctions
+. etc/tools/makeExtraThirdPartyFunctions
 #------------------------------------------------------------------------------
 
 # export WM settings in a form that GNU configure recognizes
@@ -58,12 +75,38 @@ echo Start ThirdParty Allwmake
 echo ========================================
 echo
 
+if isMinGW; then
+    echo ========================================
+    echo Compile zlib library
+    echo
+    ./AllwmakeZLib
+
+    echo ========================================
+    echo Compile regex library
+    echo
+    ./AllwmakeRegEx
+
+    echo ========================================
+    echo Copying gcc related DLLs
+    echo
+    cp $WM_COMPILER_DIR/bin/*.dll $FOAM_LIBBIN
+    cp $WM_COMPILER_DIR/$WM_COMPILER_ARCH/lib/*.dll $FOAM_LIBBIN
+fi
+
 
 echo ========================================
 echo Build MPI libraries if required
 echo
+
+if isMinGW; then # MPI MinGW
+
+    ./AllwmakeMinGWMPI
+
+else # MPI linux
+
 case "$WM_MPLIB" in
 OPENMPI)
+
     if [ -r $MPI_ARCH_PATH/lib${WM_COMPILER_LIB_ARCH}/libmpi.so ]
     then
         echo "    have $WM_MPLIB shared library ($FOAM_MPI)"
@@ -110,6 +153,7 @@ OPENMPI)
     ;;
 
 MPICH)
+
     if [ -r $MPI_ARCH_PATH/lib/libmpich.so ]
     then
         echo "    have $WM_MPLIB shared library ($FOAM_MPI)"
@@ -169,6 +213,8 @@ MPICH)
 
 esac
 
+fi # MPI MinGW or Linux
+
 
 # get SCOTCH_VERSION, SCOTCH_ARCH_PATH
 if settings=`$WM_PROJECT_DIR/bin/foamEtcFile config/scotch.sh`
@@ -179,6 +225,14 @@ else
     echo "Error: no config/scotch.sh settings"
     echo
 fi
+
+#either build the MinGW version or the standard version
+if isMinGW; then
+
+  ./AllwmakeMinGWScotch
+
+else
+
 
 # building scotch is still a bit of a pain
 echo ========================================
@@ -303,6 +357,7 @@ then
     }
 fi
 
+fi #end if isMinGW
 
 # -----------------------------------------------------------------------------
 
@@ -318,6 +373,25 @@ fi
 if [ -d "$METIS_VERSION" ]
 then
 
+  if isMinGW; then
+
+    if [ -f $METIS_ARCH_PATH/include/metis.h \
+      -a -r $FOAM_EXT_LIBBIN/libmetis.dll ]
+    then
+        echo "    metis header in $METIS_ARCH_PATH/include"
+        echo "    metis libs   in $FOAM_EXT_LIBBIN"
+        echo
+    else
+        set -x
+        #cd $METIS_VERSION  || exit 1
+        #make config shared=1 prefix=$METIS_ARCH_PATH
+        #make -j $WM_NCOMPPROCS install
+        #cp $METIS_ARCH_PATH/lib/libmetis.{a,dll} $FOAM_EXT_LIBBIN
+        set +x
+    fi
+
+  else
+
     if [ -f $METIS_ARCH_PATH/include/metis.h \
       -a -r $FOAM_EXT_LIBBIN/libmetis.so ]
     then
@@ -330,7 +404,11 @@ then
         make config shared=1 prefix=$METIS_ARCH_PATH
         make -j $WM_NCOMPPROCS install
         cp $METIS_ARCH_PATH/lib/libmetis.so $FOAM_EXT_LIBBIN
+        set +x
     fi
+
+  fi
+
 else
     echo "    optional component Metis was not found"
 fi
@@ -342,6 +420,20 @@ echo Build CGAL
 if [ -n "$CGAL_ARCH_PATH" ]
 then
 (
+
+  if isMinGW; then
+
+    if [ -r $CGAL_ARCH_PATH/lib/libCGAL.dll ]
+    then
+        echo "    CGAL headers in $CGAL_ARCH_PATH/include"
+        echo "    CGAL libs    in $CGAL_ARCH_PATH/lib"
+    else
+        :
+        #./makeCGALMinGW
+    fi
+
+  else
+
     if [ -r $CGAL_ARCH_PATH/lib/libCGAL.so ]
     then
         echo "    CGAL headers in $CGAL_ARCH_PATH/include"
@@ -349,6 +441,32 @@ then
     else
         ./makeCGAL
     fi
+
+  fi
+)
+else
+    echo "    optional component was not found"
+fi
+
+# -----------------------------------------------------------------------------
+
+# Tecio is optional
+echo ========================================
+echo Build Tecio
+if [ -d tecio ]
+then
+(
+    set -x
+    cd tecio || exit 1
+    cpMakeFiles tecio
+
+    if isMinGW && [ ! -e "mingw.patch.complete" ]; then
+        chmod -R +w *
+        patch -p1 < $WM_THIRD_PARTY_DIR/etc/patches/patch_tecio2009 && \
+          touch mingw.patch.complete
+    fi
+
+    wmake libso tecsrc
 )
 else
     echo "    optional component was not found"
